name: Deploy to VPS

on:
  push:
    branches:
      - master  # Trigger deployment on pushes to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

    - name: Deploy to VPS
      run: |
        ssh root@203.161.43.18 << 'EOF'
          cd /var/www/maxbet/metabet247

          # Pull the latest changes
          git pull origin master

          # Navigate to 'admin' directory, install dependencies and build
          cd admin
          npm install
          npm run build
          cd ..

          # Navigate to 'agent' directory, install dependencies and build
          cd agent
          npm install
          npm run build
          cd ..

          # Navigate to 'exchange' directory, install dependencies and build
          cd exchange
          npm install
          npm run build
          cd ..

          # Optionally, restart any necessary services (e.g., PM2)
          pm2 restart all
        EOF
